name: 'NR_AWS_integration_apply'

on:
#   push:
#     branches: [ "master" ]
    
  workflow_dispatch:
    
    
jobs:
  tfapply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION: us-east-1
      NEWRELIC_ACCOUNT_ID : ${{ secrets.NEWRELIC_ACCOUNT_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1


    - name: Terraform Init
      run: terraform init -reconfigure

#     - name: Terraform Format
#       run: terraform fmt -check
      
    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan '-var-file=terraform.tfvars' 'newrelic_account_id=${{ env.NEWRELIC_ACCOUNT_ID }}'
      
    - name: Terraform plan status
      if: steps.plan.outcome == 'failure'
      run: echo "Oops not done!"

#     - name: Terraform Apply
#       if: steps.plan.outcome != 'failure'
#       run: terraform apply -auto-approve -input=false
